name: todo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.11.0
  timezone: ^0.9.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/todoapp_icon.png"
  adaptive_icon_background: "#00000000"  
  adaptive_icon_foreground: "assets/icons/todoapp_icon.png"

flutter:
  assets:
    - assets/icons/todoapp_icon.png
  uses-material-design: true
